Images:
  ApiServer: quay.io/opendatahub/ds-pipelines-api-server:latest
  Artifact: quay.io/opendatahub/ds-pipelines-artifact-manager:latest
  OAuthProxy: registry.redhat.io/openshift4/ose-oauth-proxy:v4.12.0
  PersistentAgent: quay.io/opendatahub/ds-pipelines-persistenceagent:latest
  ScheduledWorkflow: quay.io/opendatahub/ds-pipelines-scheduledworkflow:latest
  Cache: registry.access.redhat.com/ubi8/ubi-minimal:8.8
  MoveResultsImage: registry.access.redhat.com/ubi8/ubi-micro:8.8
  MariaDB: registry.redhat.io/rhel8/mariadb-103:1
  MlmdEnvoy: quay.io/opendatahub/ds-pipelines-metadata-envoy:latest
  MlmdGRPC: quay.io/opendatahub/ds-pipelines-metadata-grpc:latest
  MlmdWriter: quay.io/opendatahub/ds-pipelines-metadata-writer:latest
  CRDViewer: gcr.io/ml-pipeline/viewer-crd-controller:2.0.0-rc.2
  VisualizationServer: gcr.io/ml-pipeline/visualization-server:2.0.0-rc.2
ImagesV2:
  Argo:
    ApiServer: quay.io/rmartine/apiserver:v2
    Artifact: quay.io/opendatahub/ds-pipelines-artifact-manager:main
    PersistentAgent: quay.io/rmartine/persistenceagent-dev:6b8723529
    ScheduledWorkflow: quay.io/rmartine/swf-dev:6b8723529
    Cache: registry.access.redhat.com/ubi8/ubi-minimal:8.7
    MoveResultsImage:  registry.access.redhat.com/ubi8/ubi-micro:8.7
    MlmdEnvoy: gcr.io/ml-pipeline/metadata-envoy:2.0.0-rc.2
    MlmdGRPC: gcr.io/tfx-oss-public/ml_metadata_store_server:1.5.0
DSPO:
  HealthCheck:
    Database:
      ConnectionTimeout: 15s
    ObjectStore:
      ConnectionTimeout: 15s
  RequeueTime: 15s
